# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matchInfo',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('matchDate', models.DateField()),
                ('matchTime', models.TimeField()),
                ('matchLocation', models.CharField(max_length=100)),
                ('numberRounds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='matchRounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('homeTeamScore', models.IntegerField()),
                ('awayTeamScore', models.IntegerField()),
                ('matchInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.matchInfo')),
            ],
        ),
        migrations.CreateModel(
            name='matchType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fightsperRound', models.IntegerField()),
                ('maxRounds', models.IntegerField()),
                ('maxScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teamInfo',
            fields=[
                ('teamName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='scoreboard.teamInfo'),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='scoreboard.teamInfo'),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='matchtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.matchType'),
        ),
    ]
