# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20170131_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtype',
            name='maxRounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchtype',
            name='maxScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
