# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 01:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20170131_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfo',
            name='matchComplete',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 1, 19, 29, 743648, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
