# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_matchinfo_matchcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='matchComplete',
            field=models.BooleanField(),
        ),
    ]
