# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_auto_20170915_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfo',
            name='matchnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
