# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0008_matchinfo_matchnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='teamColors',
            field=models.CharField(default=b'#ffffff,#ffffff', max_length=100),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='teamImage',
            field=models.CharField(default=b'ACL_defaul.png', max_length=100),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='teamLocation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
